# Generated by Django 5.2.8 on 2025-12-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Enter the student's full name", max_length=200, verbose_name='Full Name')),
                ('university_id', models.CharField(help_text='Unique university identification number', max_length=20, unique=True, verbose_name='University ID Number')),
                ('age', models.PositiveIntegerField(help_text='Age in years', verbose_name='Age')),
                ('date_of_birth', models.DateField(help_text='Birth date in YYYY-MM-DD format', verbose_name='Date of Birth')),
                ('address', models.TextField(help_text='Full residential address', verbose_name='Address')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly salary amount', max_digits=10, verbose_name='Salary')),
                ('photo', models.ImageField(help_text='Profile photo', upload_to='photos/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
